<a href="https://colab.research.google.com/github/50221181/Jeremy-rep1/blob/main/50221181_HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## HW 1 
Answer folloing questions using tensorflow's gradient tape.  

EX)
```
input_var = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
   result = tf.square(input_var)
gradient = tape.gradient(result, input_var)
```

### Q1 Differentiate $y = x^2 + 3x + 1$ with respect to a scalar variable $x$.

In [ ]:
import tensorflow as tf
x = tf.Variable(0.)
with tf.GradientTape() as tape:
  y = x ** 2 + 3 * x + 1
  grad_of_y_wrt_x = tape.gradient(y, x)


In [ ]:
grad_of_y_wrt_x


<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

### Q2 Differentiate $y = X^3 + 3X + 5$ with respect to a 2 by 2 matrix variable $X$.

In [ ]:
x = tf.Variable(tf.random.uniform((2, 2)))
with tf.GradientTape() as tape:
    y = x ** 3 + 3 * x + 5
grad_of_y_wrt_x = tape.gradient(y, x)

In [ ]:
grad_of_y_wrt_x



<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3.0002205, 3.160333 ],
       [5.6461673, 5.437517 ]], dtype=float32)>

### Q3 Differentiate $z = X^3 y^2 + 3X + 2xy + 1$ with respect to a 2 by 2 matrix variable $X$ and a scalar variable $y$.

In [6]:
import tensorflow as tf

X = tf.Variable(tf.random.uniform((2, 2)))
y = tf.Variable(0.)
tf.pow(X, y)
with tf.GradientTape() as tape:
        z = X ** 3 * y ** 2 + 3 * X + 2 * X * y + 1
grad_of_z_wrt_X_and_y = tape.gradient(z, [X, y])

In [7]:
grad_of_z_wrt_X_and_y


[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[3., 3.],
        [3., 3.]], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.4997895>]